### ISSUE TITLE
Undefined is not an object (evaluating this.props.signInWithPhone(string).)

### ISSUE THREAD

**Issue by pravinraut809** [TylerStanish/react-native-phone-auth-component#1]
First screen is loading and when i press button getting this error ,,pls help

**Comment by TylerStanish** [comment]
Did you provide a signInWithPhone prop to the PhoneAuth component that is a function that returns a Promise? Please post your code so I can diagnose this

**Comment by pravinraut809** [comment]
import React from 'react';
import {
  View,
  Dimensions,
  Text,
  Keyboard,
  Animated,
  AppState,
  TextInput,
  Platform
} from 'react-native';
import Button from './Button';
import CountryPicker from 'react-native-country-picker-modal';
import PropTypes from 'prop-types';

const {width} = Dimensions.get('window');

/*
*
* SCRUM
*
* 1. Make sure they have flex: 1 on parent
* 2. Test
*
*
* */

class PhoneVerifyScreen extends React.Component{

  constructor(p){
    super(p);
    this.state = {
      number: '',
      code: '',
      keyboardHeight: 0,
      countryInfo: {
        cca2: 'US',
        callingCode: '1',
      },

      verifying: true,
      verifyOpacity: new Animated.Value(0),
      redeemOpacity: new Animated.Value(0),

      appState: '',

      loading: false,
      loadingRedeem: false
    };
    this.styles = {
      phoneAuthText: {
        fontSize: width/10,
        alignItems: 'center',
        // borderBottomWidth: 1,
        // borderBottomColor: this.props.color,
        // textDecorationLine: 'underline',
        margin: 10,
        fontFamily: Platform.OS === 'android' ? this.props.androidFont : this.props.iOSFont
      },
      finePrint: {
        fontSize: 12,
        color: 'gray',
        marginHorizontal: 15,
        marginTop: 10
      }
    };
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange.bind(this));
  }

  _handleAppStateChange(nextAppState){
    if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
      if(this._ref) {
        this._ref.focus();
      }
      if(this._ref2){
        this._ref2.focus();
      }
    }
    this.setState({appState: nextAppState});
  }

  componentDidMount(){
    AppState.addEventListener('change', this._handleAppStateChange.bind(this));
    let bla = Keyboard.addListener('keyboardDidShow', (e) => {
      this.setState({keyboardHeight: e.endCoordinates.height});
    });
    this._ref.focus();
    Animated.timing(this.state.verifyOpacity, {toValue: 1}).start();
  }

  renderAreaCode(){
    let arr = [];
    let numbers = this.state.number.split('').slice(0, 3);
    for(let i=0; i<3; i++){
      if(isNaN(numbers[i])) numbers[i] = '_';
    }
    // we can use indexOf here because it returns the first index that it encounters '_'
    let next = numbers.indexOf('_');

    arr.push(React.createElement(
      Text,
      { key: Math.random(), style: this.styles.phoneAuthText },
      "("
    ));
    numbers.map((num, index) => {
      let color = 'black';
      if(index === next) color = this.props.color;
      arr.push(React.createElement(
        Text,
        { key: index, style: [this.styles.phoneAuthText, { color }] },
        num
      ));
    });
    arr.push(React.createElement(
      Text,
      { key: Math.random(), style: this.styles.phoneAuthText },
      ")"
    ));
    return arr;
  }

  renderNumber(){
    let arr = [];
    let numbers = this.state.number.split('').slice(0, 10);
    for(let i=0; i<10; i++){
      if(isNaN(numbers[i])) numbers[i] = '_';
    }
    let next = numbers.indexOf('_');
    numbers.slice(3, 6).map((num, index) => {
      let color = 'black';
      if(index+3 === next) color = this.props.color;
      arr.push(React.createElement(
        Text,
        { key: index + 100, style: [this.styles.phoneAuthText, { color }] },
        num
      ));
    });
    arr.push(React.createElement(
      Text,
      { key: Math.random(), style: this.styles.phoneAuthText },
      "-"
    ));
    numbers.slice(6, 10).map((num, index) => {
      let color = 'black';
      if(index+6 === next) color = this.props.color;
      arr.push(React.createElement(
        Text,
        { key: index, style: [this.styles.phoneAuthText, { color }] },
        num
      ));
    });
    return arr;
  }

  renderCode(){
    let arr = [];
    let numbers = this.state.code.split('');
    for(let i=0; i<this.props.codeLength; i++){
      if(isNaN(numbers[i])) numbers[i] = '_';
    }
    let next = numbers.indexOf('_');
    numbers.map((num, index) => {
      let color = 'black';
      if(index === next) color = this.props.color;
      arr.push(React.createElement(
        Text,
        { key: index, style: [this.styles.phoneAuthText, { color, fontSize: width / this.props.codeLength }] },
        num
      ));
    });
    return arr;
  }

  verify(){
    this.setState({loading: true});
    let string = `+${this.state.countryInfo.callingCode}${this.state.number}`;
    this.props.signInWithPhone(string).then(() => {
      Animated.timing(this.state.verifyOpacity, {toValue: 0}).start(() => {
        this.setState({verifying: false}, () => {
          Animated.timing(this.state.redeemOpacity, {toValue: 1}).start();
        });
      });
    }).finally(() => {
      this.setState({loading: false});
    });
  }

  redeemCode(){
    this.setState({loadingRedeem: true});
    this.props.redeemCode(Number(this.state.code)).catch(() => {
      this.setState({loadingRedeem: false});
    });
  }


  render(){

    let verifying = (
      <Animated.View style={{
        marginTop: 100,
        flex: 1,
        marginBottom: this.state.keyboardHeight+20,
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        opacity: this.state.verifyOpacity
      }}>
        <View style={{alignItems: 'center'}}>
          <View style={{flexDirection: 'row', alignItems: 'center'}}>
            <CountryPicker
              cca2={this.state.countryInfo.cca2}
              onChange={e => {
                this.setState({countryInfo: e}, () => {
                  this._ref.focus();
                });
              }}
              onClose={() => this._ref.focus()}
              filterable
              closeable
            />
            <Text style={this.styles.phoneAuthText}>+{this.state.countryInfo.callingCode}</Text>
            {this.renderAreaCode()}
          </View>
          <View style={{flexDirection: 'row'}}>{this.renderNumber()}</View>
        </View>
        <TextInput
          ref={ref => this._ref = ref}
          keyboardType={'phone-pad'}
          style={{position: 'absolute', top: -100, left: -100}}
          value={this.state.number}
          onChangeText={num => {
            if(num.length < 11){
              this.setState({number: num});
            }
          }}
        />
        <View style={{alignItems: 'center', width: '100%'}}>
          <Button
            title={this.props.verifyButtonMessage}
            backgroundColor={this.props.color}
            onPress={() => this.verify()}
            loading={this.state.loading}
            spinnerColor={this.props.spinnerColor}
            textColor={this.props.buttonTextColor}
          />
          <Text style={this.styles.finePrint}>{this.props.disclaimerMessage}</Text>
        </View>
      </Animated.View>
    );

    let redeeming = (
      <Animated.View style={{
        opacity: this.state.redeemOpacity,
        marginBottom: this.state.keyboardHeight+20,
        justifyContent: 'space-between',
        alignItems: 'center',
        flex: 1
      }}>
        <TextInput
          autoFocus
          keyboardType={'phone-pad'}
          style={{position: 'absolute', top: -100, left: -100}}
          value={this.state.code}
          onChangeText={num => {
            if(num.length < this.props.codeLength+1){
              this.setState({code: num});
            }
          }}
          ref={ref => this._ref2 = ref}
        />
        <View/>
        <View style={{flexDirection: 'row'}}>{this.renderCode()}</View>
        <Button
          title={this.props.enterCodeMessage}
          backgroundColor={this.props.color}
          loading={this.state.loadingRedeem}
          onPress={() => this.redeemCode()}
          textColor={this.props.buttonTextColor}
          spinnerColor={this.props.spinnerColor}
        />
      </Animated.View>
    );

    return(
      <View style={this.props.containerStyle}>
        {this.state.verifying ? verifying : redeeming}
      </View>
    );
  }
}

// list of all RN fonts can be found at https://github.com/react-native-training/react-native-fonts
PhoneVerifyScreen.propTypes = {
  color: PropTypes.string,
  buttonTextColor: PropTypes.string,
  spinnerColor: PropTypes.string,
  redeemCode: PropTypes.func.isRequired,
  signInWithPhone: PropTypes.func.isRequired,
  androidFont: PropTypes.string,
  iOSFont: PropTypes.string,
  containerStyle: PropTypes.object,
  verifyButtonMessage: PropTypes.string,
  enterCodeMessage: PropTypes.string,
  disclaimerMessage: PropTypes.string,
  codeLength: PropTypes.number
};

PhoneVerifyScreen.defaultProps = {
  color: '#ff8203',
  buttonTextColor: 'white',
  spinnerColor: 'white',
  redeemCode: () => console.log('Please attach method to redeemCode prop'),
  signInWithPhone: () => console.log('Please attach method to signInWithPhone prop'),
  androidFont: 'monospace',
  iOSFont: 'Menlo',
  containerStyle: {flex: 1},
  verifyButtonMessage: 'Verify Phone Number*',
  enterCodeMessage: 'Enter code',
  disclaimerMessage: '*Message & data rates may apply.',
  codeLength: 4
};

export default PhoneVerifyScreen;

**Comment by TylerStanish** [comment]
Ok, you should not be using the code from the src folder from my package. I see you joined GitHub a short time ago so I get you're new with this.
You should be doing ```npm install --save react-native-phone-auth-component``` from your project's folder in your terminal and then doing 
```javascript
import React from 'react';
import PhoneAuth from 'react-native-phone-auth-component';
export default class extends React.Component{

  redeem(code){
    console.log(code);
    // push to new screen,  route, whatever
    return Promise.resolve();
  }

  signIn(phoneNumber){
    console.log(phoneNumber);
    // verify the user's phone number
    return Promise.resolve();
  }

  render(){
    return(
      <PhoneAuth redeemCode={this.redeem.bind(this)} signInWithPhone={this.signIn.bind(this)}/>
    );
  }
}
```
in a file, say, Auth.js.

Whenever you want to use an NPM module you should use ```import``` or ```require()``` rather than copy-pasting code from the source.

**Comment by pravinraut809** [comment]
Okay ,, i will keep your code as reference .. Thank u Sir..

**Comment by pravinraut809** [comment]
Plss,,   i am trying whole day ..and getting same error....pls

**Comment by TylerStanish** [comment]
Ok, I don't really know how to help you because my example works. If you're new to React Native I suggest you learn more about how React Native works first.
