### ISSUE TITLE
can't find variables :axios

### ISSUE THREAD

**Issue by shyam1211** [TylerStanish/react-native-phone-auth-component#2]
i have an issue with axios ,when i tapped on verify phone number button ,it shows an error but already i install react-native-axios 
please resolve this issue
thanks in advance

**Comment by TylerStanish** [comment]
In your JS are you importing from react-native-axios? Because react-native-axios does not exist on its own, instead you should ```npm install axios``` and then
```javascript
import axios from 'axios';
```
and then use axios as you normally would

**Comment by TylerStanish** [comment]
I'm assuming there's no problem here, closing now

**Comment by shyama-9932** [comment]
Thanks@TylerStanish.
Nows,its working
