### ISSUE TITLE
How can I change country code ?

### ISSUE THREAD

**Issue by rahu431** [TylerStanish/react-native-phone-auth-component#5]

**Comment by rahu431** [comment]
I found, when I press flag icon it shows country dropdown to select. and 
# How to set default country code to "India +91" , because depend on app usage prefer the country code.
# one more favor can add code sample with firebase phone auth.

**Comment by TylerStanish** [comment]
As of version 0.1.4 I have added the props ```cca2``` and ```callingCode``` to allow you to specify the default values for these items

**Comment by TylerStanish** [comment]
I don't have any public backend firebase code. I don't use Firebase much anymore, but all you have to do is call admin.auth().createCustomToken(phoneNumber) for your phone authentication Firebase setup and it will send you a token which you can log in the user like in the Readme
