### ISSUE TITLE
unable to receive code on my number

### ISSUE THREAD

**Issue by naveedshahji** [TylerStanish/react-native-phone-auth-component#8]
First of all thank you for such a great guide.
 I am using it without axios npm.
my code is like 
 signInWithPhone(phone){
    console.log("Promise.resolve() Value is ",Promise.resolve());
    return Promise.resolve();
}
Promise.resolve() Value is ====> Promise {
  "_40": 0,
 "_55": undefined,
   "_65": 1,
   "_72": null,
 } 
 the second screen display successfully but the code is not sent to the phone number. i tried with different phone number but code is not sending.
Kindly help me.

**Comment by naveedshahji** [comment]
Can any one help me. am I doing something wrong.

**Comment by naveedshahji** [comment]
I also tried it with the following lines  but code is not sending to my number
async signInWithPhone(phone){
   try {
    console.log("try",phone);
    let success = await Promise.resolve();
    return success ;  
  } catch (error) {
      console.log("Error Sending code" + error);
      return null
  }

**Comment by TylerStanish** [comment]
This component does not send any text messages on its own, it is only a UI component

**Comment by naveedshahji** [comment]
oh sorry I was waiting all the day for the message.

**Comment by naveedshahji** [comment]
ok apart from it, can you share the sending code as you have done in demo, as i am unable to solve it

**Comment by TylerStanish** [comment]
In the demo I am interacting with a backend API (via axios). You should send the text message from the backend (never from the front end) with a service like Twilio

**Comment by naveedshahji** [comment]
thanks for the reply!
basically I want to do it in firebase. on firebase website there is a help for web but I am unable to do it in react-native.
for web "firebase.auth().signInWithPhoneNumber(phoneNumber, appVerifier)"  I am rtying something like that but unable because appVerifier need http or https.
I am stuck here from couple of days. and search on different forums but cant find any help for firebase with react-native.

**Comment by TylerStanish** [comment]
Sorry I can't really help you with that. This is a forum for issues related to this react native component
