### ISSUE TITLE
Number format?

### ISSUE THREAD

**Issue by tofsjonas** [TylerStanish/react-native-phone-auth-component#9]
Like your thingy!

Is there any way to change the number format? In Sweden we don't have the 555-1234 format you do in the States...

**Comment by TylerStanish** [comment]
Yeah I'll try adding a prop where you do something like `phoneSpacing='(***)***-****'` to represent the amount of digits in parenthesis (if any), dashes, etc, after the country code

**Comment by tofsjonas** [comment]
Wonderful :)

**Comment by TylerStanish** [comment]
Hi so actually I'm really busy and I don't know if I can spend much time on this project anymore, but I tried my best and made some changes where you can specify a `phoneLength` prop which is the length of the phone number (not including country code) and it takes a number

But you'll have to add it to your dependencies as `"react-native-phone-auth-component": "TylerStanish/react-native-phone-auth-component#phoneSize"` see [this](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a) as an example of taking a dependency from a github branch
